# These are supported funding model platforms

github: [zonuexe] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
custom: ["https://www.pixiv.net/fanbox/creator/105589"] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
